### ISSUE TITLE
dplyr 1.1.0 compatibility 

### ISSUE THREAD

**Issue by DavisVaughan** [sametsoekel/kmscv#1]
Hi there, your package was flagged in our revdep check for the upcoming release of dplyr 1.1.0. I was going to send a PR here, but it seems like this repo is not up to date. Can you please look here instead? https://github.com/cran/kmscv/pull/1

**Comment by sametsoekel** [comment]
Hi, thanks for the reminder. I created https://github.com/sametsoekel/kmscv/pull/2 PR. After checking `--as-cran` and comparing it to the old benchmark tests I will merge them.
